### ISSUE TITLE
asking for dataset

### ISSUE THREAD

**Issue by kongshuchen** [daicoolb/PHDMF#1]
I am intrested in your paper but i can not get the datset from the link you given in your paper. Can you share your datasets used in your paper for me? Thank you! ^_^

**Comment by daicoolb** [comment]
the datasets you can download it from movielens and amazon, just google is ok.

**Comment by kongshuchen** [comment]
But I found that the plot summaries for the movielen dataset are not available. How can i get the plot summaries for the data in movielen?

**Comment by daicoolb** [comment]
you can scarp it from http://www.imdb.com or just download the dataset from ConvMF.

**Comment by kongshuchen** [comment]
sorry, the link given from ConvMF to download the dataset is unavailable and i can not concat the author of this paper.

**Comment by kongshuchen** [comment]
sorry, the link given from ConvMF to download the dataset is unavailable and i can not concat the author of this paper.

**Comment by daicoolb** [comment]
OK . I will push my data to my server in  next week . now I am outside.

**Comment by rahimentezari** [comment]
I am also was wondering if you would upload your dataset, specially binary vectors for user side information. I have no idea to binarize my user side information.

**Comment by yushuai** [comment]
Hope to access to the dataset via GitHub, sigh... Thanks!!!
