### ISSUE TITLE
How to compute h(L) 

### ISSUE THREAD

**Issue by s1162276945** [daicoolb/PHDMF#4]
l = 1, 2, ...L − 1
we can get h0~h(L-1)
But how to compute h(L)  ?

**Comment by s1162276945** [comment]
I mean how can we get h(L) from h(L-1) to h(L)

**Comment by daicoolb** [comment]
what's your meaning with h(L)

**Comment by s1162276945** [comment]
> what's your meaning with h(L)

h(L) means the L-th hidden layer.

**Comment by daicoolb** [comment]
if you want to compute the h(L)， just get it from h(L-1), the last layer is just like the input layer.

**Comment by s1162276945** [comment]
> if you want to compute the h(L)， just get it from h(L-1), the last layer is just like the input layer.

So h(L) = h(L-1), is it right?

**Comment by daicoolb** [comment]
h(L) = w * h(L-1) +b
