### ISSUE TITLE
how to convert to one host.

### ISSUE THREAD

**Issue by noone513** [daicoolb/PHDMF#8]
For example I have data for side information of ml-1m below.
1::F::1::10::48067
2::M::56::16::70072
3::M::25::15::55117
4::M::45::7::02460
5::M::25::20::55455
6::F::50::9::55117
7::M::35::1::06810

--> could you help me to convert above data to one host?
Thank you!

**Comment by daicoolb** [comment]
just make the largest id  to the length of the data
